# Generated by Django 4.0.3 on 2022-03-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sylvanapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PlayStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sylvanapi.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sylvanapi.player')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attending', through='sylvanapi.EventPlayer', to='sylvanapi.player'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizing', to='sylvanapi.player'),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('commander', models.CharField(max_length=1000)),
                ('creatures', models.CharField(max_length=1000)),
                ('artifacts', models.CharField(max_length=1000)),
                ('enchantments', models.CharField(max_length=1000)),
                ('instants', models.CharField(max_length=1000)),
                ('sorceries', models.CharField(max_length=1000)),
                ('lands', models.CharField(max_length=3000)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('powerLevel', models.IntegerField()),
                ('primer', models.CharField(max_length=5000)),
                ('play_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sylvanapi.playstyle')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sylvanapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=1000)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sylvanapi.deck')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sylvanapi.player')),
            ],
        ),
    ]
