# Generated by Django 4.0.3 on 2022-03-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sylvanapi', '0002_event_playstyle_eventplayer_event_attendees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='play_style',
            new_name='playStyle',
        ),
    ]
